### ISSUE TITLE
version for browser

### ISSUE THREAD

**Issue by rbellens** [appsup-dart/firebase_dart#1]
Currently only works on server as it depends on the `WebSocket` class in `dart:io`.

Create a `Transport` that works with the `WebSocket` class in `dart:html`.

**Comment by Zectbumo** [comment]
I get the error
The requested built-in library is not available on Dartium.'package:firebase_dart/src/protocol.dart': error: line 8 pos 1: library handler failed
import 'dart:io';
^: package:firebase_dart/src/protocol.dart

**Comment by rbellens** [comment]
Currently only server is supported.
A browser version should be ready in a few days.
