### ISSUE TITLE
Handle errors

### ISSUE THREAD

**Issue by giaur500** [appsup-dart/firebase_dart#15]
In example:
```
var ref = new Firebase("https://n6ufdauwqsdfmp.firebaseio-demo.com/");

  ref.child("test").onValue.listen((e) {
    print(e.snapshot.val);
  });
```
If there's no internet or url is invalid or child does not exists - how to catch error? Without it, library is useless. Currently, if no internet connection, listen is never executed, but I am unable to catch there was some error.

**Comment by BwanaBuna** [comment]
I am experiencing the same issue

**Comment by ylahav** [comment]
Similar to that: How can we check if file exist?
Something like this:
ref.child("test").isExist()

**Comment by giaur500** [comment]
I think the only way is to use timeout - I mean, need to wait a few seconds, if no response, assume error. Something like this:

```
DataSnapshot dataSnapshot = await ref
      .child("test")
      .onceValue
      .timeout(
        (const Duration(seconds: 15)),
        onTimeout: () => null,
      );
```

**Comment by rbellens** [comment]
With firebase realtime databases, a query should not fail when there is no internet connection. Instead, the client waits until there is an internet connection and a connection can be established with the server. Similarly when a connection is lost, the client will try to reestablish a connection as soon as possible and reregister all the listeners and possibly unsent writes. This way, you do not need to worry about recovering from unstable internet connections. See also the documentation of firebase on offline capabilities, e.g. https://firebase.google.com/docs/database/android/offline-capabilities. 

If you need to know if there is an active connection with the server, you can listen to the data at `.info/connected`. See also the firebase documentation here https://firebase.google.com/docs/database/android/offline-capabilities#section-connection-state. E.g.:

```dart
rootRef.child('.info/connected').onValue.listen((e) {
  print('connected: ${e.snapshot.val}');
});
```

Similarly, it is not considered an error to listen for data at a location where there is currently no data, as an error would cancel the subscription and you might want to get notified when data is written to that location. Instead, a location with no data is considered to have the value `null`. So, you can check if there is data at a particular location, as follows:

```dart
var hasData = (await ref.child('some/path').get())!=null;
```
