### ISSUE TITLE
How to do? Firestore Database

### ISSUE THREAD

**Issue by anandsubbu007** [appsup-dart/firebase_dart#19]
Hi, I'm New to this.

may I know how to push and fetch data To & From Firebase Database.

i tried but it doesn't works
```
 var ref = db.reference().child('test');
    await ref.set({
      'Value': {'One': 1, 'Two': 2, 'Three': 3}
    });
    await ref.set({'Box': json});
    await ref.update({"Box": json});
```

Thanks For Your Contribution.

**Comment by rbellens** [comment]
Can you give a bit more context? Maybe a full example of what is failing? Do you get an error?

**Comment by anandsubbu007** [comment]
Function run completely.
No error found.

When I check my firebase db manually. There is no change in firebase db.

**Comment by rbellens** [comment]
I'm afraid, I won't be able to help you if I don't get any more info. The code above should work. So, maybe there is some problem in the initialization or something, but I would need the full example code to judge.

**Comment by anandsubbu007** [comment]
```
      FirebaseDart.setup(storagePath: dir.path);
      firebaseApp = await Firebase.initializeApp(
          options: FirebaseOptions.fromMap(firebaseConfig));
    FirebaseDatabase db = FirebaseDatabase(
        app: Firebase.app(), databaseURL: 'mem://Subbu.App/');
    await db.goOnline();
    Map json = {'One': 1, 'Two': 2, 'Three': 3};
    var ref = db.reference().child('test');
    await ref.set('{"Box": "json"}');
    await ref.set({'Box': json});
    await ref.update({"Box": "json"});
```
tried this code

**Comment by anandsubbu007** [comment]
Does it supports Firestore Database in Firebase?

**Comment by rbellens** [comment]
no, only realtime database, storage and authentication for now

**Comment by rbellens** [comment]
Ah, yes, but you're using an in memory database url `mem://Subbu.App/`. This creates a database in the local memory and won't synchronize with any server. Main purpose for an in memory database is for unit testing. You should instead use an url that points to the actual database. In general, this is something like: `https://my-project.firebaseio.com`. Probably, it is already part of your `firebaseConfig` variable, so you don't need to explicitly add it anymore when you create the `FirebaseDatabase` instance. Simply, do:

```dart
var db = FirebaseDatabase(app: firebaseApp);
```
