### ISSUE TITLE
How does this package store the signed in user?

### ISSUE THREAD

**Issue by DirtyNative** [appsup-dart/firebase_dart#26]
I am trying to implement this library into my app and found something I don't understand:
When I sign in with email and password, I get back the UserCredentials.
Now the official Firebase auth package does not need any additional code to stay signed in. If I reload the app, I am still signed in.

When I use this package and reload after I signed in, it seems I am not anymore. Do I have to store something like a token after I sign in?

**Comment by rbellens** [comment]
This package uses the `Hive` package to store persistent data. Depending on which platform you're using, you need to initialize this. See the [getting started instructions](https://pub.dev/packages/firebase_dart).
