### ISSUE TITLE
Is persistence supported?

### ISSUE THREAD

**Issue by DirtyNative** [appsup-dart/firebase_dart#27]
Does this package support offline storage for the realtime db? I set the desired persistence path, but it does not seem any files are written there, and if I try to get some data when I got no internet connection, the code is stock within the get method.

If this is not supported, what would be the preferred way to store the data and sync when going online again?

Thanks for your help!

**Comment by rbellens** [comment]
Persistent data storage is supported.
For the real time database you need to call `db.setPersistenceEnabled(true)` to enable it.
