### ISSUE TITLE
Null check operator used on a null value?

### ISSUE THREAD

**Issue by fenchai23** [appsup-dart/firebase_dart#29]
just trying the library and I can't even get authenticated lol.

```
C:\Users\someUser\Desktop\dart\projects\firebase_test>dart run
Building package executable...
Built firebase_test:firebase_test.
Unhandled exception:
Null check operator used on a null value
#0      _processResponse (package:openid_client/src/http_util.dart:34:26)
#1      get (package:openid_client/src/http_util.dart:17:10)
<asynchronous suspension>
#2      Issuer.discover (package:openid_client/src/openid.dart:127:16)
<asynchronous suspension>
#3      Client.forIdToken (package:openid_client/src/openid.dart:151:18)
<asynchronous suspension>
#4      RpcHandler._credentialFromIdToken (package:firebase_dart/src/auth/rpc/rpc_handler.dart:245:9)
<asynchronous suspension>
#5      FirebaseAuthImpl.signInWithEmailAndPassword (package:firebase_dart/src/auth/impl/auth.dart:95:13)
<asynchronous suspension>
#6      main (file:///C:/Users/someUser/Desktop/dart/projects/firebase_test/bin/firebase_test.dart:18:14)
<asynchronous suspension>
```

what I have done:

- created a user with email and password
- tried to sign in

am I doing something incorrectly?
```
Future<void> main() async {
  FirebaseDart.setup(storagePath: 'storage');

  var app = await Firebase.initializeApp(
      options: FirebaseOptions.fromMap(
          json.decode(File('firebase-config.json').readAsStringSync())));

  var auth = FirebaseAuth.instanceFor(app: app);

  var user = await auth.signInWithEmailAndPassword(
      email: 'ferdinand99_firebase@gmail.com',
      password: 'someRandomPassword88');

  print(user.user?.email);
}

```

**Comment by dcagyemang-pros** [comment]
It has something to do with the file you're printing
You're printing a null value, try logging instead, that way you'll see the full data

**Comment by fenchai23** [comment]
> It has something to do with the file you're printing
> You're printing a null value, try logging instead, that way you'll see the full data 

that's not it.

I even removed that print statement and it still gives the same error.

**Comment by leviabellar** [comment]
**I got the same issue with "await auth.signInAnonymously();"**


Unhandled exception:
Null check operator used on a null value
#0      _processResponse (package:openid_client/src/http_util.dart:34:26)
#1      get (package:openid_client/src/http_util.dart:17:10)
<asynchronous suspension>
#2      Issuer.discover (package:openid_client/src/openid.dart:127:16)
<asynchronous suspension>
#3      Client.forIdToken (package:openid_client/src/openid.dart:151:18)
<asynchronous suspension>
#4      RpcHandler._credentialFromIdToken (package:firebase_dart/src/auth/rpc/rpc_handler.dart:245:9)
<asynchronous suspension>
#5      FirebaseAuthImpl.signInAnonymously (package:firebase_dart/src/auth/impl/auth.dart:80:15)
<asynchronous suspension>
#6      main (file:///C:/Users/HP/Desktop/Work/dart%20apps/firebase_dart/cli/bin/cli.dart:35:3)
<asynchronous suspension>

**Comment by DirtyNative** [comment]
I am getting the same error with an app which did not change anything the last few days. Suddenly I get that error.. It seems like firebase itself changed some api calls which this library cannot handle

**Comment by fenchai23** [comment]
> I am getting the same error with an app which did not change anything the last few days. Suddenly I get that error.. It seems like firebase itself changed some api calls which this library cannot handle

if that's the reason then we are in trouble 😅 I had to allow all read & write from my storage at the moment.

Any alternatives to access firebase storage on dart at the moment?

**Comment by rbellens** [comment]
In version 0.13.5 of the `http` package, there is a breaking change that causes this issue. I will fix this incompatibility in the next version (1.0.11). For now, forcing version 0.13.4 of the http package should fix this issue.
