### ISSUE TITLE
How to get lists from the database?

### ISSUE THREAD

**Issue by TimWhiting** [appsup-dart/firebase_dart#31]
In the official firebase implementations, you can store Json lists (internally they are just recognized as Maps that have sequential numbering starting from zero). When attempting to do that with this library, I am able to save lists, but when reading them back, they end up as maps. This causes problems with json serialization libraries.

Any recommended way to approach this? Making everything maps is not the solution I'm looking for.

**Comment by TimWhiting** [comment]
Simple sample:
```dart
import 'package:firebase_dart/core.dart';
import 'package:firebase_dart/database.dart';
import 'package:firebase_dart/implementation/testing.dart';

void main(List<String> arguments) async {
  await FirebaseTesting.setup();

  var app = await Firebase.initializeApp(
    options: FirebaseOptions(
      appId: 'appid',
      apiKey: 'apiKey',
      authDomain: 'authDomain',
      databaseURL: 'mem://database',
      projectId: 'projectId',
      storageBucket: 'storageBucket',
      messagingSenderId: 'messagingSenderId',
    ),
  );
  var backend = FirebaseTesting.getBackend(app.options);
  final root = FirebaseDatabase(app: app).reference();
  await root.child('test').set({
    'hi': ['test', 'test2']
  });
  print(await root.child('test').get());
}
```

prints... `{hi: {0: test, 1: test2}}` when I expect `{hi: [test, test2]}`

**Comment by Andro999b** [comment]
Can this be configurable? I have opposite case when int is map key. And because of this logic item can be either list or map...
