### ISSUE TITLE
Auth persistence

### ISSUE THREAD

**Issue by vd3d** [appsup-dart/firebase_dart#34]
Hi,

I have see that the credential persistence is not supported for now.

But, is there a way to implement it by ourself, or an alternative?

By example, if at some point we receive a token and later we can authenticate with this token (by example)?
In such case, we can store the token locally (and not the user/password by example)

**Comment by rbellens** [comment]
Yes, sure: 

The `Credential` class has a `toJson` method and `fromJson` constructor which can be used to serialize and deserialize. This also (de)serializes all the openid provider metadata, which is maybe unnecessary and prevents getting the latest version. 
Alternatively, you could simply store the fields of the `TokenResponse` class and create a new `Credential` with the `Client.createCredential`. 

There is a `onTokenChanged` getter in the `Credential` class that returns a stream that emits a `TokenResponse` every time the tokens are refreshed. So, you can listen to this stream and store an update of the tokens.

To pro-actively refresh the token, you can set timers for when the token is about to expire and call `credential.getTokenResponse(true)` to force a token refresh. Or, simply use a periodic timer, e.g. every minute, and call `credential.getTokenResponse()`. This will only refresh the token, when it has expired.

**Comment by rbellens** [comment]
The credentials are persisted to disk.

Maybe, you didn't initialize correctly. You should however call the following command first: 

```dart
FirebaseDart.setup(storagePath: 'path/to/persistent/storage');
```

**Comment by vd3d** [comment]
Thanks,

Noticed that I'm on Windows and for now I only use email/password :-)

But still, when I call : _instance.setPersistence(Persistence.local)   ... I got an "unimplemented" exception !

PS: yes I initialized the storage correctly.

**Comment by rbellens** [comment]
The `setPersistence` method is indeed currently not implemented, but that only means you can not disable persistent storage. So, you should not call that method for now.

I have not tested on windows yet. For the persistent storage, the [hive](https://pub.dev/packages/hive) package is used under the hood. This should however work on windows as well. 

As you are using flutter, do you use `firebase_dart_flutter`?

**Comment by vd3d** [comment]
It was not working... but indeed, I do not use firebase_dart_flutter.
Why do we need such package ? What does it bring ?

**Comment by rbellens** [comment]
`firebase_dart_flutter` uses some flutter plugins to implement some features that are otherwise not possible. E.g. it uses `path_provider` to find a suitable location to store persistent data on different platforms. However, you should also be able to set it manually. You could check the storagePath you use for files with extension `.hive`. Do they exist?

Other features that `firebase_dart_flutter` brings are things like facebook and google sign in and phone verification with sms.

**Comment by vd3d** [comment]
Wonderful, thanks ;-)
