### ISSUE TITLE
get() occasionally waits forever 

### ISSUE THREAD

**Issue by MELICI0US** [appsup-dart/firebase_dart#35]
I've been seeing an issue that pops up every once in a while. A get() on a piece of the database just waits forever and times out. All of the following get() calls do the same. We think that it might have something to do with re-authentication with a service account using the firebase_admin package

**Comment by rbellens** [comment]
Hi @MELICI0US.
Thanks for your report. It's a bit difficult to debug without a reproducible example. Can you provide one, or is it just happening randomly? Which version are you using? I know similar behavior happened on some older versions, but that was fixed.

**Comment by MELICI0US** [comment]
The project is using firebase_dart: 1.1.0-dev.9 and firebase_admin: 0.3.0-dev.4 at the moment. It happens pretty randomly. I see it about once in every 4 or 5 full app tests, and have not encountered it during smaller development testing.

**Comment by rbellens** [comment]
@MELICI0US, I've fixed an issue in version 1.1.0-dev.10. Not sure if this is the issue you encounter, but it could certainly explain it. Could you check if you still have the issue with the latest version.
