### ISSUE TITLE
Decoded headers map from token doesn't contain kid key. 

### ISSUE THREAD

**Issue by bettdouglas** [appsup-dart/firebase_dart#37]
Hello and many thanks for this awesome package. I was trying to create to validate tokens sent from the client to my server. Using the package `firebase_auth_admin_verify` successfully verifies tokens generated from `firebase_core` and `firebase_auth`., but when I try with this package, it says No kid available. 

Could you please assist me with pointing out this issue or if the problem is in the `firebase_auth_admin_verify` package?

```dart 
import 'package:firebase_auth_admin_verify/firebase_auth_admin_verify.dart';
import 'package:firebase_dart/firebase_dart.dart';
import 'package:firebase_dart/implementation/testing.dart';
import 'package:test/test.dart';

void main() {
  test('verifies token successfully', () async {
    final token = await _getTestToken();
    final jwt = await verifyFirebaseToken(
      token,
      serviceFilePath: 'service-account.json',
      projectId: 'my_project',
    );
  });
}

Future<String> _getTestToken() async {
  await FirebaseTesting.setup();

  final app = await Firebase.initializeApp(
    options: FirebaseOptions(
        appId: 'my_app_id',
        apiKey: 'apiKey',
        projectId: 'my_project',
        messagingSenderId: 'ignore',
        authDomain: 'my_project.firebaseapp.com'),
  );
  var backend = FirebaseTesting.getBackend(app.options);

  final email = 'intergration_test_email@gmail.com';
  final password = 'password';

  final user = await backend.authBackend.createUser(
    email: email,
    password: password,
  );

  // final token = await backend.authBackend.generateIdToken(uid: uid, providerId: providerId)
  var auth = FirebaseAuth.instanceFor(app: app);
  final cred = await auth.signInWithEmailAndPassword(
    email: email,
    password: password,
  );
  return await backend.authBackend.generateIdToken(
    uid: cred.user!.uid,
    providerId: cred.additionalUserInfo!.providerId!,
  );
}



```

**Comment by rbellens** [comment]
Hi @bettdouglas,
The `generateIdToken` in this package is intended for testing purposes only. It will not generate valid id tokens that can be used outside this testing environment. The `kid` (key id) parameter is indeed not added, as the key used is a temporary key only used in this testing environment. 
What exactly are you trying to accomplish?

**Comment by bettdouglas** [comment]
Hello thanks for the reply.

I'm trying to write a server side grpc interceptor to be used to make sure requests coming to the server are authenticated by Firebase. The package I'm using has to use key-id to verify the certificate. 

From your explanation, it seems Firebase native clients are the only ones who can create valid idTokens or is there a way to generate tokens for a integration test environment?

**Comment by rbellens** [comment]
I don't think the native clients generate id tokens. It would not be secure. The tokens are generated on the firebase servers when authenticating and passed to the client. This package does the exact same thing. 
For testing: I could add the `kid` field, but I don't think that will help without having some way to use it to get the public key to verify the id token. Which package do you use to do the verification?

**Comment by bettdouglas** [comment]
Hello @rbellens I use this package [firebase_auth_admin_verify](https://pub.dev/packages/firebase_auth_admin_verify). It uses the kid to download the certificate the last time I checked. 

Thanks for your answer. It seems I'll have to use the real implementation instead of the FirebaseTesting class.  

Is it okay if I close this issue here?

**Comment by bettdouglas** [comment]
closing this since I've decided to use the `FirebaseDart.setup()` instead of `FirebaseTesting`. And this works well.
