### ISSUE TITLE
[ SocketException: Failed host lookup] is occurring when we close our internet connection 

### ISSUE THREAD

**Issue by nikirana22** [appsup-dart/firebase_dart#39]
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: SocketException: Failed host lookup: 's-apse1a-nss-2005.asia-southeast1.firebasedatabase.app' (OS Error: No such host is known.

, errno = 11001)
#0      _NativeSocket.startConnect (dart:io-patch/socket_patch.dart:694:35)
#1      _RawSocket.startConnect (dart:io-patch/socket_patch.dart:1855:26)
#2      RawSocket.startConnect (dart:io-patch/socket_patch.dart:27:23)
#3      RawSecureSocket.startConnect (dart:io/secure_socket.dart:297:22)
#4      SecureSocket.startConnect (dart:io/secure_socket.dart:77:28)
#5      _ConnectionTarget.connect (dart:_http/http_impl.dart:2462:26)
#6      _HttpClient._getConnection.connect (dart:_http/http_impl.dart:2906:12)
#7      _HttpClient._getConnection (dart:_http/http_impl.dart:2911:12)
#8      _HttpClient._openUrl (dart:_http/http_impl.dart:2766:12)
#9      _HttpClient.openUrl (dart:_http/http_impl.dart:2604:7)
#10     _WebSocketImpl.connect (dart:_http/websocket_impl.dart:1021:42)
#11     WebSocket.connect (dart:_http/websocket.dart:320:22)
#12     new IOWebSocketChannel.connect (package:web_socket_channel/io.dart:80:28)
#13     connect (package:firebase_dart/src/database/impl/connections/protocol/websocket_io.dart:4:60)
#14     Transport.open (package:firebase_dart/src/database/impl/connections/protocol/transport.dart:34:32)
#15     Connection.open (package:firebase_dart/src/database/impl/connections/protocol/connection.dart:36:15)
#16     PersistentConnectionImpl._openNetworkConnection (package:firebase_dart/src/database/impl/connections/protocol/persistent_connection.dart:617:58)
#17     PersistentConnectionImpl._tryScheduleReconnect.<anonymous closure> (package:firebase_dart/src/database/impl/connections/protocol/persistent_connection.dart:586:13)
<asynchronous suspension>

This error is occurring even if I'm not pushing any data on firebase . Called only two firebase method FirebaseDart.setup(isolated: true); , FirebaseStorage.instanceFor(app: _firebaseApp);

**Comment by rbellens** [comment]
now fixed and released in v1.1.0
