### ISSUE TITLE
Please upgrade to intl: ^0.18.0

### ISSUE THREAD

**Issue by eximius313** [appsup-dart/firebase_dart#44]
Because Flutter `3.10.0` depends on `intl: ^0.18.0` it is not possible to use `firebase_dart` which depend on `intl: ^0.17.0`
Could you please upgrade it?

**Comment by rbellens** [comment]
I'll upgrade soon. Note, you probably can use dependency_overrides in your pubspec.yaml to use intl 0.18.0 anyway.

**Comment by 0ttik** [comment]
@rbellens, what are your plans on upgrading for this case? using dependency override because of an outdated dependency is a temporary solution and a workaround.

**Comment by eximius313** [comment]
@rbellens, humble reminder...

**Comment by eximius313** [comment]
@rbellens any news on this one?

**Comment by rbellens** [comment]
now fixed and released in v1.1.0

**Comment by eximius313** [comment]
Awesome! Thank you
