### ISSUE TITLE
Please upgrade to intl: ^0.19.0

### ISSUE THREAD

**Issue by HarukaOki** [appsup-dart/firebase_dart#53]
Because Flutter `3.22.0` depends on `intl: ^0.19.0` it is not possible to use `firebase_dart` which depend on `intl: ^0.18.0`
Could you please upgrade it?

**Comment by sgehrman** [comment]
?

**Comment by RagehAz** [comment]
Any updates on this ? please upgrade to ^0.19.0, I can't continue working and don't know how to workaround this situation..
appreciate your effors

**Comment by Timothy-Moultt** [comment]
I'm having the same issue, please upgrade to ^0.19.0
